# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_DEVAPC_MT6893) += device-apc-mt6893.o
device-apc-mt6893-$(CONFIG_DEVAPC_MT6893) += devapc-mt6893.o
device-apc-mt6893-$(CONFIG_DEVAPC_ARCH_MULTI) += devapc-mtk-multi-ao.o
