# TALIH-PD2 (MT8797/MT6893) TWRP BoardConfig
# TWRP-in-boot: 内核 + 原厂 dtb + TWRP recovery ramdisk 打包为 boot 镜像

DEVICE_PATH := device/talih/pd2

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_BOARD_PLATFORM := mt6893
TARGET_BOOTLOADER_BOARD_NAME := pd2

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false

# 预编译内核（resukisu-susfs 分支产物: ReSukiSU + SUSFS）
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_INCLUDE_RECOVERY_DTBO := false

# MTK boot image 参数（与原厂 boot header 一致）
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_OFFSET := 0x00080000
BOARD_RAMDISK_OFFSET := 0x11100000
BOARD_TAGS_OFFSET := 0x07c80000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 buildvariant=user
BOARD_BOOT_HEADER_VERSION := 2
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_PAGE_SIZE := 2048
BOARD_FLASH_BLOCK_SIZE := 131072

# 文件系统
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SUPPRESS_SECURE_ERASE := true

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/etc/twrp.fstab
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
BOARD_HAS_NO_SELECT_BUTTON := true

# 屏幕（2560x1600 横屏平板）
DEVICE_RESOLUTION := 2560x1600
TW_SCREEN_WIDTH := 2560
TW_SCREEN_HEIGHT := 1600
TW_THEME := landscape_hdpi

# 背光
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 160

# 加密（FBE v2 f2fs + MTK inline crypto，TEE 换钥大概率无法解密，保留尝试能力）
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_USE_FSCRYPT_POLICY := 2
TW_INCLUDE_FBE_METADATA_DECRYPT := false

# A/B 无独立 recovery 分区（recovery-as-boot，TWRP 打进 boot）
TW_HAS_NO_RECOVERY_PARTITION := true

TW_NO_REBOOT_BOOTLOADER := true
TW_NO_SCREEN_BLANK := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_LIBRESETPROP := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_REPACKTOOLS := true
TW_USE_TOOLBOX := true
TW_DEFAULT_DEVICE_NAME := TALIH-PD2
TW_EXTRA_LANGUAGES := true
TW_NO_LEGACY_PROPS := true
TW_CUSTOM_CPU_TEMP_PATH := "/sys/class/thermal/thermal_zone0/temp"

PLATFORM_SECURITY_PATCH := 2099-12-31
