aw883xx_smartpa-objs := aw883xx.o aw883xx_monitor.o aw883xx_bin_parse.o \
	aw883xx_device.o aw883xx_init.o aw883xx_calib.o aw883xx_spin.o \
	aw883xx_ext.o

obj-$(CONFIG_TCT_SMARTPA_AW883XX) += aw883xx_smartpa.o
